trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/employees/urls.py
from django.urls import path

from . import views

# TODO: Determine what distinct pages are required for the customer user stories, add a path for each in urlpatterns

app_name = "employees"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name='create'),
    path('my_accounts/', views.my_accounts, name='my_accounts'),
    path('confirm_pickup/<int:customer_id>/', views.confirm_pickup, name='confirm_pickup'),
    path('<int:customer_id>/profile/', views.customer_profile, name="customer_profile"),
    path('edit_profile/', views.edit_profile, name="edit_profile")
]

trash_collector/trash_collector/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First adding our custom routes from our accounts app's urls.py (for our custom registration)
    path('accounts/', include('accounts.urls')),
    # Then adding Django's built in routes (login and logout). Notice there is no 'login' function in accounts/views.py. Django takes care of this for us.
    path('accounts/', include('django.contrib.auth.urls')),
    # Adding all urls from customer app
    path('customers/', include('customers.urls')),
    # Adding all urls from employees app
    path('employees/', include('employees.urls')),
    # 'home' redirects a user to the appropriate index based on their auth group. Investigate trach_collector/views.py for more info
    path('', views.group_redirect, name='home')
]

trash_collector/employees/models.py
from django.db import models

# Create your models here.

# TODO: Create an Employee model with properties required by the user stories

class Employee(models.Model):
    user = models.ForeignKey('accounts.User', blank=True, null=True, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    zip_code = models.IntegerField()

    def __str__(self):
        return self.first_name + " " + self.last_name

trash_collector/employees/views.py
from .models import Employee
from django.http.response import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.shortcuts import render
from django.apps import apps
from datetime import date
import calendar
import requests

# Create your views here.

#Displays pickupsf for:
    #Customers in employee zip code, where pickup day is today & service is not suspended OR there is a 1-time pickup scheduled for today
@login_required
def index(request):
    user = request.user

    try:
        # This line inside the 'try' will return the customer record of the logged-in user if one exists
        logged_in_employee = Employee.objects.get(user=user)
    except:
        return HttpResponseRedirect(reverse('employees:create'))
    today = date.today()
    today_weekday = calendar.day_name[today.weekday()]
    Customer = apps.get_model('customers.Customer')
    employee_geocode = geocode_address(logged_in_employee.zip_code)
    emp_lat = employee_geocode['lat']
    emp_lng = employee_geocode['lng']
    employee_lat_lng = {
        'lat': emp_lat,
        'lng': emp_lng
    }
    
    matching_customers = Customer.objects.filter(zip_code=logged_in_employee.zip_code).filter(weekly_pickup=today_weekday).exclude(date_of_last_pickup=today).exclude(suspend_start__lte=today, suspend_end__gte=today)
    customer_onetime_pickup = Customer.objects.filter(zip_code=logged_in_employee.zip_code).filter(one_time_pickup=today).exclude(date_of_last_pickup=today).exclude(suspend_start__lte=today, suspend_end__gte=today)

    customer_geocodes = []
    for customer in matching_customers:
        customer_full_address = customer.address + ' '+ customer.zip_code
        customer_geocode = geocode_address(customer_full_address)
        lat = customer_geocode['lat']
        lng = customer_geocode['lng']
        formatted_lat_lng = {
            'lat': lat,
            'lng': lng
        }
        customer_geocodes.append(formatted_lat_lng)
    for customer in customer_onetime_pickup:
        customer_full_address = customer.address + ' '+ customer.zip_code
        customer_geocode = geocode_address(customer_full_address)
        lat = customer_geocode['lat']
        lng = customer_geocode['lng']
        formatted_lat_lng = {
            'lat': lat,
            'lng': lng
        }
        customer_geocodes.append(formatted_lat_lng)

    context = {
        'matching_customers': matching_customers,
        'customer_geocodes': customer_geocodes,
        'employee_lat_lng': employee_lat_lng,
        'customer_onetime_pickup': customer_onetime_pickup,
        'logged_in_employee': logged_in_employee
    }
    return render(request, 'employees/index.html', context)

#Display all ccustomers in zip code, option to filter by pickup day
@login_required
def my_accounts(request):
    user = request.user
    logged_in_employee = Employee.objects.get(user=user)
    Customer = apps.get_model('customers.Customer')
    matching_customers = []
    
    if(request.method == "POST" and request.POST.get("pickup_day") != "All"):
        pickup_day = request.POST.get("pickup_day")
        all_customers = Customer.objects.filter(weekly_pickup=pickup_day)
    else:
        all_customers = Customer.objects.all()

    context = {
        'matching_customers': all_customers
    }

    return render(request, 'employees/my_accounts.html', context)

@login_required
def create(request):
    if request.method == "POST":
        user = request.user
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        zip_code = request.POST.get('zip_code')
        new_customer = Employee(user=user, first_name=first_name, last_name=last_name, zip_code=zip_code)
        new_customer.save()
        context = {
            'logged_in_employee': new_customer
        }
        return render(request, 'employees/index.html', context)
    else:
         return render(request, 'employees/create.html')

@login_required
def confirm_pickup(request, customer_id):
    Customer = apps.get_model('customers.Customer')
    customer = Customer.objects.get(id=customer_id)
    if request.method == "POST":
        customer.balance += 20
        customer.date_of_last_pickup = date.today()
        customer.save()
        
        return HttpResponseRedirect(reverse('employees:index'))
    else:
        context = {
            'customer': customer
        } 
        return render(request, 'employees/confirm_pickup.html', context)

        

@login_required
def customer_profile(request, customer_id):
    logged_in_user = request.user
    logged_in_employee = Employee.objects.get(user=logged_in_user)

    Customer = apps.get_model('customers.Customer')
    customer = Customer.objects.get(pk=customer_id)
    customer_address = customer.address
    customer_zip = customer.zip_code
    customer_full_address = customer_address + ' '+ customer_zip
    customer_geocode = geocode_address(customer_full_address)
    #customer_url = urllib.parse.quote(customer_full_address)
    
    context = {'customer': customer,
                'logged_in_employee': logged_in_employee,
                'customer_full_address': customer_full_address,
                'customer_geocode': customer_geocode,
                'cust_lat': customer_geocode['lat'],
                'cust_long': customer_geocode['lng']
                }
    
    return render (request, 'employees/customer_profile.html', context)

def geocode_address(address):
    geo_request = requests.get(f'https://maps.googleapis.com/maps/api/geocode/json?address={address}&key=APIKEYHERE!')
    if geo_request.status_code == 200:
        response = geo_request.json()
        lat_lng = response['results'][0]['geometry']['location']
        return lat_lng
        #default returns Uluru, as to not break app
    else: 
        return { 'lat': -25.344, 'lng': 131.036 }

def edit(request):
    if request.method == "POST":
        user = request.user
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        zip_code = request.POST.get('zip_code')
        new_customer = Employee(user=user, first_name=first_name, last_name=last_name, zip_code=zip_code)
        new_customer.save()
        return render(request, 'employees/index.html')
    else:
         return render(request, 'employees/create.html')

@login_required
def edit_profile(request):
    logged_in_user = request.user
    logged_in_employee = Employee.objects.get(user=logged_in_user)
    if request.method == "POST":
        name_from_form = request.POST.get('first_name')
        last_name_from_form = request.POST.get('last_name')
        zip_from_form = request.POST.get('zip_code')
        logged_in_employee.first_name = name_from_form
        logged_in_employee.last_name = last_name_from_form
        logged_in_employee.zip_code = zip_from_form
        logged_in_employee.save()
        return HttpResponseRedirect(reverse('employees:index'))
    else:
        context = {
            'logged_in_employee': logged_in_employee
        }
        return render(request, 'employees/edit_profile.html', context)

trash_collector/employees/templates/employees/confirm_pickup.html
{% extends 'employees\employee_base.html' %}

{% block title %}Confirm Customer Pickup{% endblock %}

{% block content %}
<h4>Confirm Pickup for:</h4>
<h4>{{ customer.name }}</h4>

<form action ="{% url 'employees:confirm_pickup' customer.id %}", method="POST">
    {% csrf_token %}

    <button type="submit" class="btn btn-sm btn-outline-success">Confirm Pickup</button>
</form>
<a class="btn btn-sm btn-outline-success" href="{% url 'employees:index' %}">Return Home</a>
    
{% endblock %}

trash_collector/employees/templates/employees/create.html
{% extends 'employees\employee_base.html' %}

{% block title %}Employee Account Creation{% endblock %}

{% block content %}

    <form action ="{% url 'employees:create' %}", method="POST">
        {% csrf_token %}
        First Name: <input type="text", name="first_name", id="first_name"><br />
        Last Name: <input type="text", name="last_name", id="last_name"><br />
        Zip Code: <input type="text", name="zip_code", id="zip_code"><br />
        <input type="submit" value="Create Account!">
    </form>
    
{% endblock %}

trash_collector/employees/templates/employees/customer_profile.html
{% extends 'employees\employee_base.html' %}
{% block script %} 
 {% endblock %}

{% block title %}Customer Profile{% endblock %}

{% block content %}

<h1>Address On File For {{customer.name}}:</h1>
<p>{{customer.name}}'s Home Address & Zip Code: {{customer_full_address}}</p>
<div id="map" class="map"></div>
<a class="btn btn-sm btn-outline-success" href="{% url 'employees:index' %}">Return to Home</a>
{% endblock %}

{% block footercontent %}
<script async
src="https://maps.googleapis.com/maps/api/js?v=3&key=APIKEYHERE&callback=initMap">
</script>
<script>
    function initMap() {

    var lat_lng = { lat: {{cust_lat}}, lng: {{cust_long}} }
    console.log(lat_lng)
    var options = {
          center: lat_lng,
        zoom: 14
    };
      const map = new google.maps.Map(document.getElementById("map"), options);
      const marker = new google.maps.Marker({
        position: lat_lng,
        map: map,
      });
    }
    </script>

{% endblock %}

trash_collector/employees/templates/employees/edit_profile.html
{% extends 'employees\employee_base.html' %}

{% block title %} Customer Profile Edit {% endblock %}

{% block header %} Update Your Information {% endblock %}

{% block content %}
<br />
<form action="{% url 'employees:edit_profile' %}" method="post">
    {% csrf_token %}
    First Name: <input type="text" name="first_name" id="first_name" value="{{logged_in_employee.first_name}}">
    <br />
    <br />
    Last Name: <input type="text" name="last_name" id="last_name" value="{{logged_in_employee.last_name}}">
    <br />
    <br />
    Zip Code: <input type="text" name="zip_code" id="zip_code" value="{{logged_in_employee.zip_code}}">
    <br />
    <br />
    <input type="submit" value="Submit">
</form>

{% endblock %}

trash_collector/employees/templates/employees/employee_base.html
{% extends 'base.html' %}
{% block navbar %}
<a class="nav-item nav-link" href="{% url 'employees:index' %}">Home</a>
<a class="nav-item nav-link" href="{% url 'employees:my_accounts' %}">My Accounts</a>
<a class="nav-item nav-link" href="{% url 'employees:edit_profile' %}">Edit Profile</a>
{% endblock %}

trash_collector/employees/templates/employees/index.html
{% extends 'employees\employee_base.html' %}

{% block title %}{% block header %} Employee Home {% endblock %}{% endblock %}

{% block content %}
  {% if user.is_authenticated %}

  <h4>Today's Pickups for {{logged_in_employee.first_name}}</h4>
  <table>
    <tr>
      <th>Customer</th>
      <th>Zip Code</th>
      <th>Balance</th>
      <th>View Profile</th>
      <th>Confirm Pickup</th>
    </tr>
    {% for customer in matching_customers %}
    <tr>
      <td>{{customer.name}}</td>
      <td>{{customer.zip_code}}</td>
      <td>{{customer.balance}}</td>
      <td><a class="btn btn-sm btn-outline-success" href="{% url 'employees:customer_profile' customer.id %}">View Profile</a>
      </td>
      <td><a class="btn btn-sm btn-outline-success" href="{% url 'employees:confirm_pickup' customer.id %}">Confirm Pickup</a>
      </td>
    </tr>
    {% endfor %}
  </table>
</br>
</br>

  <h4>Today's One-Time Pickups</h4>
  <table>
    <tr>
      <th>Customer</th>
      <th>Zip Code</th>
      <th>Balance</th>
      <th>View Profile</th>
      <th>Confirm Pickup</th>
    </tr>
    {% for customer in customer_onetime_pickup %}
    <tr>
      <td>{{customer.name}}</td>
      <td>{{customer.zip_code}}</td>
      <td>{{customer.balance}}</td>
      <td><a class="btn btn-sm btn-outline-success" href="{% url 'employees:customer_profile' customer.id %}">View Profile</a>
      </td>
      <td><a class="btn btn-sm btn-outline-success" href="{% url 'employees:confirm_pickup' customer.id %}">Confirm Pickup</a>
      </td>
    </tr>
    {% endfor %}
  </table>
</br>
</br>

  <div id="map" class="map"></div>
  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}

{% block footercontent %}
<script async
src="https://maps.googleapis.com/maps/api/js?v=3&key=APIKEYHERE&callback=initMap">
</script>
<script>
    function initMap() {
    var options = {
        center: {{employee_lat_lng | safe}},
        zoom: 14
    };
    var customer_geocodes = {{customer_geocodes | safe}}
    console.log(customer_geocodes)
      const map = new google.maps.Map(document.getElementById("map"), options);
      for (let i=0; i< customer_geocodes.length;i++){
        var marker = new google.maps.Marker({
          position: customer_geocodes[i],
          map: map,
        });
      }
    }
    </script>

{% endblock %}

trash_collector/employees/templates/employees/my_accounts.html
{% extends 'employees\employee_base.html' %}

{% block title %}{% block header %} My Accounts: {% endblock %}{% endblock %}

{% block content %}
  {% if user.is_authenticated %}

  <form action ="{% url 'employees:my_accounts' %}", method="POST">
    {% csrf_token %}
    <label for="pickup_day">Filter by Pickup Day:</label>
    <select name="pickup_day" id="pickup_day">
        <option value="All">All</option>
        <option value="Monday">Monday</option>
        <option value="Tuesday">Tuesday</option>
        <option value="Wednesday">Wednesday</option>
        <option value="Thursday">Thursday</option>
        <option value="Friday">Friday</option>
    </select>
    <input type="submit" value="Filter">
</form>
  <table>
    <tr>
      <th>Name</th>
      <th>Zip Code</th>
      <th>Pickup Day</th>
    </tr>
    {% for customer in matching_customers %}
    <tr>
      <td>{{customer.name}}</td>
      <td>{{customer.zip_code}}</td>
      <td>{{customer.weekly_pickup}}</td>

    </tr>
    {% endfor %}
  </table>
    {% for customer in matching_customers %}

    {% endfor %}
  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}